# Generated by Django 4.2.3 on 2023-07-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Full name")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, null=True, verbose_name="Birthday"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15, null=True, verbose_name="Phone number"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Home address"
                    ),
                ),
                ("birthday", models.DateField(verbose_name="Birthday")),
            ],
        ),
    ]
