# Generated by Django 4.2.3 on 2023-07-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addressbook", "0004_alter_contact_email_alter_contact_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
