# Generated by Django 4.2.3 on 2023-07-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addressbook", "0005_alter_contact_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
