version: "3.9"

services:
  web:
    build:
      context: Personal_Assistant
      dockerfile: Dockerfile
    command: uvicorn Personal_Assistant.asgi:application --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=Personal_Assistant.settings
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5432:5432"