# Generated by Django 4.2.3 on 2023-07-21 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="user",
        ),
    ]
