# Generated by Django 4.2.3 on 2023-07-22 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_app", "0002_remove_file_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="file",
        ),
    ]
