# Generated by Django 4.2.3 on 2023-07-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_app", "0007_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="category",
            field=models.CharField(),
            preserve_default=False,
        ),
    ]
